# Generated by Django 5.2.17 on 2026-09-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=50, unique=True)),
                ('claim_type', models.CharField(choices=[('MEDICAL', 'Medical / Hospitalization'), ('ACCIDENT', 'Accidental Damage'), ('THEFT', 'Loss / Theft'), ('DEATH', 'Death Claim'), ('DISABILITY', 'Critical Illness / Disability'), ('TRAVEL_DELAY', 'Travel Delay / Loss of Baggage'), ('OTHER', 'Other Incident')], default='MEDICAL', max_length=50)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='SUBMITTED', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='accounts.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='policies.policy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
